# Generated by Django 6.0.4 on 2026-05-10 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'Bitta yulduzdan kam baholash mumkin emas!'), django.core.validators.MaxValueValidator(5, "Beshta yulduzdan ko'p baholay olmaysiz!")]),
        ),
        migrations.AddField(
            model_name='new',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi'], message='Faqat .mp4 va .avi fayllar uchun ruxsat etilgan!!!')]),
        ),
    ]
